---
- name: Setup EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/infra.yml

  tasks:
    - name: Configure EC2 instances for hosting online games
      include_role:
        name: configure_ec2_instances

- name: Setup httpd
  hosts: online_games_instances
  tasks:
    - name: Configure httpd
      include_role:
        name: configure_httpd
