---
# tasks file for configure_httpd

- name: Install httpd
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ httpd_pkg_list }}"
  
- name: Copy games html
  get_url:
    url: "{{ online_game_url }}"
    dest: "/var/www/html/index.html"

- name: start httpd
  service:
    name: httpd
    state: started

- name: Get installed version of Apache.
  command: "/usr/sbin/httpd -v"
  changed_when: false
  register: _httpd_version

- name: Create apache_version variable.
  set_fact:
    httpd_version: '{{ _httpd_version.stdout.split()[2].split("/")[1] }}'

- name: Print httpd version
  debug:
    msg: "httpd_version= {{ httpd_version }}"

- name: Harden httpd server
  template:
    src: "hardening.conf.j2"
    dest: "{{ httpd_conf_dir }}/conf.d/90.hardening.conf"
    owner: root
    group: root
    mode: 0640
    backup: yes
  notify: restart httpd

- name: Flush handlers
  meta: flush_handlers

- name: Wait for Http server to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 80
    state: started

- name: Access online games at below URL
  debug:
    msg: "Access {{ online_game_name }} at http://{{ dns_name }}"
